/////////////////////////////////////////////////////////////////////////////////////////////////////////
// This configuration file was generated by the OAT Configurator at https://config.openastrotech.com for
// firmware Latest Official (V1.10.1).
// Save this as Configuration_local.hpp in the folder where you placed the firmware code.
// Unique ConfigKey: FW:O,HS:N,BD:M21,RS:N9,RD:TU,RAP900:O90:S8:T64:,RMSA3000:V1200:,RT:1,DS:N9,DD:TU,DAP900:O90:S16:T64:,DMSA3000:V1200:,DT:1,DY:LCD,GP:N,LM:Y,FC:Y,FS:BY,FD:TU,FAP150:O100:S1:H10:,FMSA600:V400:,AP:Y,AV:2,ZS:BY,ZD:TU,ZAP150:O100:H:,ZAO:N,LS:BY,LD:TU,LAP150:O100:H:,LAO:N,AH:Y

// We live in the Northern Hemisphere
#define NORTHERN_HEMISPHERE 1

#define INDI 0
#define QUICK_BOOT 0
#define TRACK_ON_BOOT 0
#define DEBUG_LEVEL (DEBUG_INFO | DEBUG_GENERAL | DEBUG_GYRO | DEBUG_MEADE | DEBUG_MOUNT | DEBUG_SERIAL)
#define DEBUG_START_LEVEL String(F("MEADE|MOUNT|SERIAL|GENERAL"))
// :GVP# :
/* time+date
:SG+01#
:Sg-11*11#  :Sg348*49#  :Sg-361*00# :Sg-11*11#
:St+48*02'03#
:SL13:43:48# :SL23:00:00#
:SC02/05/20#
:XSDMMEADE|MOUNT|SERIAL#
/ * get time
:GL#
/ * get date
:GC#
/ * Set HA
:SH19:34#
/ * HA
:XGH#
/ * Set LST
:SHL200353#
/ * LST
:XGL#
/ * Long
:Gg#
/ * Lat
:Gt#
*/
// We are using the MKS GEN L V2.1 board
#if defined(BOARD) && BOARD != BOARD_AVR_MKS_GEN_L_V21
    #error Selected PIO environment does not match this configuration
#else
    #define BOARD BOARD_AVR_MKS_GEN_L_V21
#endif

////////////////////////////////
// RA Stepper configuration 
// See supported stepper values. Change according to the steppers you are using
// Using the NEMA 17, 0.9Â°/step stepper for RA
#define RA_STEPPER_TYPE STEPPER_TYPE_ENABLE

// Using the TMC2209-UART driver for RA stepper motor
#define RA_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define some RA stepper motor settings
#define RA_MOTOR_CURRENT_RATING       900 // mA
#define RA_OPERATING_CURRENT_SETTING  90 // %
#define RA_SLEW_MICROSTEPPING         8
#define RA_TRACKING_MICROSTEPPING     64

// TMC2209 Stealth Mode (spreadCycle) - When set to 0, tracking is more precise, but noisy (high-pitched sound). When set to 1, they are silent.
#define RA_UART_STEALTH_MODE          0

// Is it going the wrong way?
// when pressing the buttons, the lower part should go in that direction
#define RA_INVERT_DIR  1

// Define some RA stepper motor settings
#define RA_STEPPER_ACCELERATION 3000
#define RA_STEPPER_SPEED 1200

// Using the 16 tooth gear (recommended) for RA belt
#define RA_PULLEY_TEETH 16

////////////////////////////////
// DEC Stepper configuration 
// See supported stepper values. Change according to the steppers you are using
// Using the NEMA 17, 0.9Â°/step stepper for DEC
#define DEC_STEPPER_TYPE STEPPER_TYPE_ENABLE

// Using the TMC2209-UART driver for DEC stepper
#define DEC_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define some DEC stepper motor settings
#define DEC_MOTOR_CURRENT_RATING       900 // mA
#define DEC_OPERATING_CURRENT_SETTING  90 // %
#define DEC_SLEW_MICROSTEPPING         16
#define DEC_GUIDE_MICROSTEPPING        64

// TMC2209 Stealth Mode (spreadCycle) - When set to 0, tracking is more precise, but noisy (high-pitched sound). When set to 1, they are silent.
#define DEC_UART_STEALTH_MODE          0

// Is it going the wrong way?
// when pressing the buttons, the front guider part should go in that direction
#define DEC_INVERT_DIR  0

// Define some DEC stepper motor settings
#define DEC_STEPPER_ACCELERATION 3000
#define DEC_STEPPER_SPEED 1200

// Using the 16 tooth gear (recommended) for DEC belt
#define DEC_PULLEY_TEETH 16

////////////////////////////////
// Display configuration 
// Define the type of display we are using. Currently: LCD Shield w/ keypad
#define DISPLAY_TYPE DISPLAY_TYPE_LCD_KEYPAD
//#define DISPLAY_TYPE DISPLAY_TYPE_NONE
#if !QUICK_BOOT
////////////////////////////////
// GPS Addon configuration 
// Define whether we have the GPS addon or not. Currently: No GPS
#define USE_GPS 0

////////////////////////////////
// Digital Level Addon configuration 
// Define whether we have the Digital Level or not. Currently: MPU-6050 Gyroscope
#define USE_GYRO_LEVEL 0
#define GYRO_AXIS_SWAP 0
// MKS uses software I2C library. Define the SCL and SDA pins you wired (recommended are 11 and 21)
#define USE_GYRO_WITH_SOFTWAREI2C 1
#define GYRO_SOFTWARE_SCL_PIN 11
#define GYRO_SOFTWARE_SDA_PIN 21
////////////////////////////////
// Focuser configuration 
// Define whether to support a focusing stepper motor on E1 or not. Currently: Focuser stepper

// Using the Modded 28BYJ-48 (Bipolar) stepper for FOC
#define FOCUS_STEPPER_TYPE STEPPER_TYPE_ENABLE
#define FOCUS_STEPPER_SPR 2048.0f

// Using the TMC2209-UART driver for focuser stepper
#define FOCUS_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define Focus stepper motor power settings
#define FOCUS_MOTOR_CURRENT_RATING       150 // mA
#define FOCUS_OPERATING_CURRENT_SETTING  100 // %
#define FOCUS_MICROSTEPPING              1 // steps
#define FOCUSER_MOTOR_HOLD_SETTING       10 // %
#define FOCUS_UART_STEALTH_MODE          1 // silent?
#define FOCUSER_ALWAYS_ON                0

// Define some focuser stepper motor settings
#define FOCUS_STEPPER_ACCELERATION 600
#define FOCUS_STEPPER_SPEED 400

////////////////////////////////
// AutoPA Addon configuration 
// Define whether we have the AutoPA add on or not. Currently: AutoPA is installed

// Using AutoPA V2.0.
#define AUTOPA_VERSION 2

// Using the Modded 28BYJ-48 (Bipolar) stepper for AZ
#define AZ_STEPPER_TYPE STEPPER_TYPE_ENABLED
#define AZ_STEPPER_SPR 2048.0f

// Using the TMC2209-UART driver for AZ stepper motor
#define AZ_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define AZ stepper motor power settings
#define AZ_MOTOR_CURRENT_RATING      150 // mA
#define AZ_OPERATING_CURRENT_SETTING 100 // %
#define AZ_MOTOR_HOLD_SETTING        0 // %

// Define AZ always-on
#define AZ_ALWAYS_ON 0

// Using the Modded 28BYJ-48 (Bipolar) stepper for ALT
#define ALT_STEPPER_TYPE STEPPER_TYPE_ENABLED
#define ALT_STEPPER_SPR 2048.0f

// Using the TMC2209-UART driver for ALT stepper motor
#define ALT_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define ALT stepper motor power settings
#define ALT_MOTOR_CURRENT_RATING      150 // mA
#define ALT_OPERATING_CURRENT_SETTING 100 // %
#define ALT_MOTOR_HOLD_SETTING        0 // %

// Define ALT always-on
#define ALT_ALWAYS_ON 0

////////////////////////////////
// Is the RA Auto Home addon installed
#define USE_HALL_SENSOR_RA_AUTOHOME 0
#endif