///////////////////////////////////////////////////////////////////////////////////////////////////////// 
// This configuration file was generated by the OAT Configurator at https://config.openastrotech.com for 
// firmware V1.9.30 and later. 
// Save this as Configuration_local.hpp in the folder where you placed the firmware code. 
 
// We live in the Northern Hemisphere 
#define NORTHERN_HEMISPHERE 1 
 
// We are using the ESP32 board 
// #define BOARD BOARD_ESP32_ESP32DEV 
 
//////////////////////////////// 
// RA Stepper configuration  
// See supported stepper values. Change according to the steppers you are using 
// Using the 28BYJ-48 stepper for RA 
#define RA_STEPPER_TYPE STEPPER_TYPE_28BYJ48 
#define RA_DRIVER_TYPE DRIVER_TYPE_ULN2003 
 
// Using the 16 tooth gear (recommended) for RA belt 
#define RA_PULLEY_TEETH 16 
 
//////////////////////////////// 
// DEC Stepper configuration  
// See supported stepper values. Change according to the steppers you are using 
// Using the 28BYJ-48 stepper for DEC 
#define DEC_STEPPER_TYPE STEPPER_TYPE_28BYJ48 
#define DEC_DRIVER_TYPE DRIVER_TYPE_ULN2003 
 
// Using the 16 tooth gear (recommended) for DEC belt 
#define DEC_PULLEY_TEETH 16 
 
//////////////////////////////// 
// Display configuration  
// Define the type of display we are using. Currently: LCD Shield w/ keypad 
#define DISPLAY_TYPE DISPLAY_TYPE_LCD_KEYPAD 
 
//////////////////////////////// 
// WiFi configuration  
// Are we using WiFi: Yes, use WiFi 
#define WIFI_ENABLED 1 
 
// Using WiFi in mode Infrastructure, all devices connect to same network 
#define WIFI_MODE WIFI_MODE_INFRASTRUCTURE 
 
// Define the SSID, WPA key and host name for the network 
#define WIFI_INFRASTRUCTURE_MODE_SSID "TP-LINK_7A8EF6" 
#define WIFI_INFRASTRUCTURE_MODE_WPAKEY "35712749" 
#define WIFI_HOSTNAME "OATScope" 
 
//////////////////////////////// 
// GPS Addon configuration  
// Define whether we have the GPS addon or not. Currently: No GPS 
#define USE_GPS 0 
 
//////////////////////////////// 
// AutoPA Addon configuration  
// Define whether we have the AutoPA add on or not. Currently: No AutoPA 
// No AutoPA settings 
 
#define DEBUG_LEVEL (DEBUG_INFO)
